[common]
bind_port = 7000
token=Phoenix123qwer!@#

# 仪表盘功能
dashboard_port = 7500
# dashboard 用户名密码，默认都为 admin
dashboard_user = admin
dashboard_pwd = Common123qwer!@#

# frp日志配置
log_file = /usr/local/frp_0.51.3_linux_amd64/frps.log
log_level = info
log_max_days = 10

